### ISSUE TITLE
blink_led for zedboard

### ISSUE THREAD

**Issue by ghost** [fractalclone/zephyr-riscv#8]
Hello, 

The README states that the blink_led programs is for the arduino board. Make BOARD=zedboard_pulpino gives errors. Is it possible to run the blink led tests for the zedboard ? 

Thank you !

**Comment by fractalclone** [comment]
@ninode blink_led requires a pwm driver and there is no pwm driver available for pulpino. But you can test the blinky application instead, which does the same stuff by just toggling a gpio. Blinky works with pulpino
